name: Test

on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Cardano node
      uses: ./
      with:
        tag: '10.1.4'

    - name: Test
      run: cardano-node --version

    - name: Install Cardano node with new prefix
      uses: ./
      with:
        tag: '8.7.3'
        prefix: 'prime'

    - name: Test
      run: prime-node --version

    - name: Install Cardano node with sufix
      uses: ./
      with:
        tag: '11.0.1'
        sufix: '11'

    - name: Test sufix
      run: |
        cardano-node-11 --version
        cardano-cli-11 --version
