name: Test

on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Cardano node
      uses: milos-ethernal/cardano-node-action@89c368c8f6a023bcc5ff9cfcc9288a1c50d18a0a
      with:
        tag: '10.1.4'

    - name: Test
      run: cardano-node --version

    - name: Install Cardano node with new prefix
      uses: milos-ethernal/cardano-node-action@89c368c8f6a023bcc5ff9cfcc9288a1c50d18a0a
      with:
        tag: '8.7.3'
        prefix: 'prime'

    - name: Test
      run: prime-node --version
