name: Test

on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Cardano node
      uses: milos-ethernal/cardano-node-action@da33943cb2cb0e56358bd5f7c12773423d02738e
      with:
        tag: '10.1.4'

    - name: Test
      run: cardano-node --version
